name: AutoReplant
version: ${project.version}
main: me.cobaltgecko.autoreplant.AutoReplant
api-version: 1.18
authors: [ CobaltGecko ]
description: A plugin allowing players to automatically replant crops
